general:
  BOT_TOKEN: 1234567890
  BOT_STATUS: SpiritMS
  THUMBNAIL_URL: ""
  PREFIX: "!"
  ADMIN_ROLE: Admin
  LOG_COMMANDS: true

  ADD_ROLE: false
  ROLE_TO_GIVE: "Role Name Here"

  SERVER_NAME: SpiritMS
  EMBED_COLOR: 0x03fcc6
  ICON_URL: "https://cdn.discordapp.com/icons/722153430457647104/ad8368ee9d687dc73aaa8f47ce0c0026.png?size=128"

connection:
  database:
    HOST: localhost
    NAME: heavenms
    USER: root
    PASS: ""

  API:
     KEY: PUTAPIKEYHERE
     HOST: "http://localhost:8080/"

  IO_API:
    REGION: GMS
    VERSION: 216

# Note that YAMl uses lowercase for Booleans
toggle:
  help: true
  info: true
  char: true
  guild: true
  rank: true
  online: true
  duey: false
  dc: true
  whisper: true
  notice: true
  unban: true
  makegm: true
  givevp: true
  giveaway: false
